### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by anfractuosity** [iliasam/STM32F4_USB_MICROPHONE#1]
Hi, 

I'm just wondering if you have the Makefile you
used to compile this?

Thanks a lot!

Chris

Edit: Just managed to get it working with gcc :)

https://github.com/anfractuosity/STM32F4Disco-Microphone

**Comment by iliasam** [comment]
Sorry, I have used IAR and it does not generate Makefile.

**Comment by anfractuosity** [comment]
No worries, it works great now with gcc for me, thanks a lot for the code!
