### ISSUE TITLE
USB_AUDIO example

### ISSUE THREAD

**Issue by romansavrulin** [iliasam/STM32F4_USB_MICROPHONE#2]
Hello! 

This is not an issue, actually. Just a request.

can you provide a repo, that was mentioned in http://we.easyelectronics.ru/STM32/primery-raboty-s-usb-device-dlya-stm32f4-discovery.html . The link to the dropbox is dead.

Thank you.

**Comment by iliasam** [comment]
Hello.
I have updated link in my article.

**Comment by romansavrulin** [comment]
Thank you a lot!
