### ISSUE TITLE
Does it compile at all?

### ISSUE THREAD

**Issue by hidefromkgb** [iliasam/STM32F4_USB_MICROPHONE#3]
Hi. I`m struggling to port this project to Keil v5.
In the source, I see e.g. this: https://github.com/iliasam/STM32F4_USB_MICROPHONE/search?q=EVAL_AUDIO_PauseResume
One formal parameter, 3 actual. By any means, that cannot be compiled.

**Comment by iliasam** [comment]
I have tested - this project is  compiling in IAR.
I did not use "usbd_audio_out_if.c" file in my project.
I make a new commit with this file deleted and small improvements.

**Comment by hidefromkgb** [comment]
Good. Considering this one fixed.
