### ISSUE TITLE
i can-t use 16k for micphone

### ISSUE THREAD

**Issue by liufulj** [iliasam/STM32F4_USB_MICROPHONE#4]
i can use the  usbd_audio_core.c  on stm32f401  with 8K  ,USBD_IN_AUDIO_FREQ ,but when i change it to 16k, it does not work ,

**Comment by iliasam** [comment]
I'm sorry, I can't help you with that.

**Comment by liufulj** [comment]
can't you give me you project for keil5?

**Comment by iliasam** [comment]
I'm sorry, but no.
You can see that this project is really old.

**Comment by liufulj** [comment]
okay , thanks
